spring.application.name=crm-notifications


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
javainuse.rabbitmq.exchange=crm.messages.exchange
javainuse.rabbitmq.queue=crm.messages.queue
javainuse.rabbitmq.routingkey=crm.messages.routingkey
